os: linux
arch: amd64
dist: bionic
language: go
go:
- "1.13.x"
go_import_path: github.com/argoproj-labs/argocd-operator
env:
  - GO111MODULE=on
cache:
  directories:
  - $GOCACHE
  - $GOPATH/pkg/mod
before_install:
  - sudo apt-get -y install bash
  - go get github.com/operator-framework/operator-sdk
script: bash hack/build.sh
