os: linux
arch: amd64
dist: bionic
language: go
go:
- "1.13.x"
go_import_path: github.com/argoproj-labs/argocd-operator
env:
  - GO111MODULE=on
cache:
  directories:
  - $GOCACHE
  - $GOPATH/pkg/mod
script: hack/build.sh
