os: linux
arch: amd64
dist: bionic
language: go
go:
- "1.13.x"
go_import_path: github.com/argoproj-labs/argocd-operator
env:
  - GO111MODULE=on
cache:
  directories:
  - $GOCACHE
  - $GOPATH/pkg/mod
before_install:
  - cd $HOME
  - git clone https://github.com/operator-framework/operator-sdk operator-framework/operator-sdk
  - cd operator-framework/operator-sdk
  - git checkout v0.17.0
  - make tidy
  - make install
  - cd $HOME/argoproj-labs/argocd-operator
script: hack/build.sh
