os: linux
arch: amd64
dist: bionic
language: go
go:
- "1.13.x"
env:
  - ARGOCD_OPERATOR_IMAGE_BUILDER=docker
  - GO111MODULE=on
cache:
  directories:
  - $GOCACHE
  - $GOPATH/pkg/mod
before_install:
  - echo "Installing podman..."
  - . /etc/os-release
  - sudo sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
  - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get -qq -y install podman
  - echo "Installing operator-sdk..."
  - git clone https://github.com/operator-framework/operator-sdk $GOPATH/src/github.com/operator-framework/operator-sdk
  - cd $GOPATH/src/github.com/operator-framework/operator-sdk
  - git checkout v0.17.0
  - make tidy
  - make install
  - cd $GOPATH/src/github.com/argoproj-labs/argocd-operator
script: bash hack/build.sh
branches:
  only: # safelist
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
