resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:405e7bde25affb7644c576a7f2d41ba30b88e2ef4f2f11945b920a33517895cee
  name: controller
  newName: quay.io/argoprojlabs/argocd-operator
