resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:2b4966b0981bae90ae36df967b7d3f2e8d99d1dc110cd09a3057e0dc688fe555
  name: controller
  newName: quay.io/argoprojlabs/argocd-operator
