resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:0189ebed00160dcc5c265f09a6d0f95089e482e01fae0c84e9dc2d4d9021eecf
  name: controller
  newName: quay.io/argoprojlabs/argocd-operator
