resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:45291354ff4b0f2899d659fe93ea449c0b150a8dfdd3324394a1613e858d8ea5
  name: controller
  newName: quay.io/argoprojlabs/argocd-operator
