resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:a35443838ddbb459f6b7c46b9b70112f1a8b69cf3b2dd107980c543d56861868
  name: controller
  newName: quay.io/argoprojlabs/argocd-operator
