apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Deep Insights
    categories: Integration & Delivery
    certified: "false"
    description: Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes.
    operators.operatorframework.io/builder: operator-sdk-v1.10.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
    repository: https://github.com/argoproj-labs/argocd-operator
    support: Argo CD
  name: argocd-operator.v0.5.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: '---description---'
  displayName: Argo CD
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - gitops
  - kubernetes
  links:
  - name: Argo CD Project
    url: https://argoproj.github.io/argo-cd/
  - name: Operator Documentation
    url: https://argocd-operator.readthedocs.io
  - name: Operator Source Code
    url: https://github.com/argoproj-labs/argocd-operator
  maintainers:
  - email: jfischer@redhat.com
    name: Jann Fischer
  maturity: alpha
  provider:
    name: Argo CD Community
  replaces: argocd-operator.v0.3.0
  version: 0.5.0
