apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: argocd-operator
  name: argocd-operator-controller-manager-metrics-service
spec:
  ports:
  - name: default-metrics
    port: 8080
    targetPort: 8080
  - name: custom-metrics
    port: 8085
    targetPort: 8085
  selector:
    control-plane: argocd-operator
status:
  loadBalancer: {}
