apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: argocd-operator.v0.0.11
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ArgoCDExport is the Schema for the argocdexports API
      kind: ArgoCDExport
      name: argocdexports.argoproj.io
      version: v1alpha1
    - description: ArgoCD is the Schema for the argocds API
      kind: ArgoCD
      name: argocds.argoproj.io
      version: v1alpha1
  displayName: Argocd Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - get
          - list
          - watch
        - nonResourceURLs:
          - '*'
          verbs:
          - get
          - list
        serviceAccountName: argocd-application-controller
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - list
        - apiGroups:
          - ""
          resources:
          - pods
          - pods/log
          verbs:
          - get
        serviceAccountName: argocd-server
      deployments:
      - name: argocd-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: argocd-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: argocd-operator
            spec:
              containers:
              - command:
                - argocd-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: argocd-operator
                image: quay.io/jmckind/argocd-operator:v0.0.9
                imagePullPolicy: Always
                name: argocd-operator
                resources: {}
              serviceAccountName: argocd-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - endpoints
          - events
          - persistentvolumeclaims
          - pods
          - secrets
          - serviceaccounts
          - services
          - services/finalizers
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - argocd-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - argoproj.io
          resources:
          - argocds
          - argocds/finalizers
          - argocds/status
          - argocdexports
          - argocdexports/finalizers
          - argocdexports/status
          verbs:
          - '*'
        - apiGroups:
          - autoscaling
          resources:
          - horizontalpodautoscalers
          verbs:
          - '*'
        - apiGroups:
          - batch
          resources:
          - cronjobs
          - jobs
          verbs:
          - '*'
        - apiGroups:
          - extensions
          resources:
          - ingresses
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - prometheuses
          - servicemonitors
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          - routes/custom-host
          verbs:
          - '*'
        serviceAccountName: argocd-operator
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - daemonsets
          - deployments
          - replicasets
          verbs:
          - '*'
        - apiGroups:
          - batch
          resources:
          - CronJob
          - Job
          verbs:
          - '*'
        - apiGroups:
          - argoproj.io
          resources:
          - applications
          - appprojects
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - list
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        serviceAccountName: argocd-application-controller
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - configmaps
          verbs:
          - get
          - list
          - watch
        serviceAccountName: argocd-dex-server
      - rules:
        - apiGroups:
          - ""
          resources:
          - endpoints
          verbs:
          - get
        serviceAccountName: argocd-redis-ha
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - configmaps
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - patch
          - delete
        - apiGroups:
          - argoproj.io
          resources:
          - applications
          - appprojects
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - delete
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - list
        serviceAccountName: argocd-server
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ""
  maintainers:
  - {}
  maturity: alpha
  provider: {}
  version: 0.0.11
