apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
spec:
  sourceType: grpc
  image: quay.io/argoprojlabs/argocd-operator-registry@sha256:1a379fea1678e66339da4f579d517d7af1cd060df101b2d08882d76d2749a990
  displayName: Argo CD Operators
  publisher: Argo CD Community
