apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
spec:
  sourceType: grpc
  image: quay.io/argoprojlabs/argocd-operator-registry@sha256:245ed329982c091ccd16bc949800c7c7a100c63182c8fbf2306cb8841e6c7dc3 # replace with your index image
  displayName: Argo CD Operators
  publisher: Argo CD Community