apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
spec:
  sourceType: grpc
  image: quay.io/argoprojlabs/argocd-operator-registry@sha256:cd3db847e1f3d6f2be71a1c904cea55622944708b4504f1824de268818b90fd3 # 0.9.2
  displayName: Argo CD Operators
  publisher: Argo CD Community