apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
spec:
  sourceType: grpc
  image: quay.io/jmckind/argocd-operator-registry@sha256:dd57daa7bd196ce1c15f71be95191a75c8e01c7a5f23fcb57763a713ed884b3d
  displayName: Argo CD Operators
  publisher: Argo CD Community
