apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
spec:
  sourceType: grpc
  image: quay.io/argoprojlabs/argocd-operator-registry@sha256:8909f3549e630d2a5b98b7b411d402003801a819523f327cc605cf4b27121ce6 # 0.10.1
  displayName: Argo CD Operators
  publisher: Argo CD Community