apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
spec:
  sourceType: grpc
  image: quay.io/argoprojlabs/argocd-operator-registry@sha256:eeebd5e3030642e89f5311249aec3b7da8cc823e1ed4863946d955d5be89b5b8
  displayName: Argo CD Operators
  publisher: Argo CD Community
