apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
spec:
  sourceType: grpc
  image: quay.io/jmckind/argocd-operator-registry@sha256:bfc3dc27ba28786d7f4e0756718bf08679075ac488b02f1f23f39f30de9f6db7
  displayName: Argo CD Operators
  publisher: Argo CD Community
