apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
spec:
  sourceType: grpc
  image: quay.io/argoprojlabs/argocd-operator-registry@sha256:d1ce402b946584fe12980160fc3543bb578312cbc409f0962be3118f480fdf90
  displayName: Argo CD Operators
  publisher: Argo CD Community
