apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
spec:
  sourceType: grpc
  image: quay.io/jmckind/argocd-operator-registry@sha256:32ff7d492a926cd21f90b7684e0a8dfd6b8d6ac6582db280d6e26c8e5a9f23a3
  displayName: Argo CD Operators
  publisher: Argo CD Community
