apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: argocd-operator
  template:
    metadata:
      labels:
        name: argocd-operator
    spec:
      serviceAccountName: argocd-operator
      containers:
        - name: argocd-operator
          image: quay.io/redhat-cop/argocd-operator@sha256:450367603cd2f3909077f854ce3b659d4c1c22490aebc11c317f97269daeae50
          command:
          - argocd-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "argocd-operator"
          resources: {}
