apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: argocd-operator
  template:
    metadata:
      labels:
        name: argocd-operator
    spec:
      serviceAccountName: argocd-operator
      containers:
        - name: argocd-operator
          image: quay.io/jmckind/argocd-operator@sha256:0ff40a548e30f89b90bbcb5ed4933d177835a4683545b78afa2133e8b1c457a6
          command:
          - argocd-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "argocd-operator"
          resources: {}
