apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
<<<<<<< HEAD
    control-plane: controller-manager
=======
    control-plane: argocd-operator
>>>>>>> master
  name: argocd-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
<<<<<<< HEAD
    control-plane: controller-manager
=======
    control-plane: argocd-operator
>>>>>>> master
status:
  loadBalancer: {}
