apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: oauth
spec:
  dex:
    image: quay.io/ablock/dex
    version: openshift-connector
    openShiftOAuth: true
  server:
    route: true
