apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: defaults
spec:
  dex:
    image: quay.io/dexidp/dex 
    version: v2.22.0
    openShiftOAuth: true
