apiVersion: v1
kind: Secret
metadata:
  name: aws-backup-secret
  labels:
    example: aws
type: Opaque
data:
  aws.access.key.id: YWNjZXNzX2tleV9pZA==
  aws.secret.access.key: c2VjcmV0X2FjY2Vzc19rZXk=
  aws.bucket.name: czM6Ly90ZXN0
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExport
metadata:
  name: example-argocdexport
  labels:
    example: aws
spec:
  argocd: example-argocd
  storage:
    backend: aws
    secretName: aws-backup-secret
