apiVersion: v1
kind: Secret
metadata:
  name: azure-backup-secret
  labels:
    example: azure
type: Opaque
data:
  azure.container.name: ZXhhbXBsZS1hcmdvY2RleHBvcnQ=
  azure.service.id: c2VydmljZV9pZA==
  azure.service.cert: c2VydmljZV9jZXJ0
  azure.storage.account: c3RvcmFnZV9hY2NvdW50
  azure.tenant.id: dGVuYW50X2lk
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExport
metadata:
  name: example-argocdexport
  labels:
    example: azure
spec:
  argocd: example-argocd
  storage:
    backend: azure
    secretName: azure-backup-secret
