name: Publish latest operator build 
on:
  push:
    branches:
      - 'master'

jobs:

  publish-latest-operator:
    runs-on: ubuntu-latest

    env:
      IMG: ${{ secrets.REGISTRY_URL }}/argocd-operator:latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Restore go build cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-v1-${{ github.run_id }}

      - name: Build operator and Tag Latest
        run: make docker-build

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push latest operator
        run: make docker-push
